UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\PCI MISO test.pfx',
    PASSWORD = 'PCITest2025!',
    CERT_DETAILS = 'C:\MISO\certs\PCI MISO test.pfx'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'AXLA',
        'CPWR',
        'MDEA01'
    )
);

UPDATE SASSET_OWNER_CONFIG
SET ACTIVE = 'N'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'AXLA');

UPDATE SASSET_OWNER_CONFIG
SET SETTLE = 'N'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'MDEA01');