UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\MEAN-PCI-1.pfx',
    PASSWORD = 'Me@nPC!121',
    CERT_DETAILS = 'C:\MISO\certs\MEAN-PCI-1.pfx'
WHERE ASSET_OWNER_KEY IN (
    SELECT so.ASSET_OWNER_KEY
    FROM SASSET_OWNER so
    INNER JOIN SISO_PORTFOLIO_MAPPING spm
        ON so.ISO_PORTFOLIO_MAPPING_KEY = spm.ISO_PORTFOLIO_MAPPING_KEY
    WHERE so.NAME IN (
        'MEAN',
        'MEAN_TEA'
        ) 
    AND spm.NAME = 'MISO'
);

UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'N',
    SETTLE = 'N'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'MEAN'
    )
);