UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\REC_PCI TEST.pfx',
    PASSWORD = 'Energy2026',
    CERT_DETAILS = 'C:\MISO\certs\REC_PCI TEST.pfx'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'REC1',
        'REC1_AO',
        'REC1_AOL'
    )
);

-- AOs are missing PROD RO permissions
UPDATE SPARAMETER SET VALUE = 'T' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_MISO_' and NAME = 'MISO_DART2_HOST_TARGET_DOWNLOADS';