UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\MISORWERPRODRO2.pfx',
    PASSWORD = 'Password123',
    CERT_DETAILS = 'C:\MISO\certs\MISORWERPRODRO2.pfx'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'CFSF',
        'EMSF',
        'LFSF',
        'QRTZ'
    )
);

UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\MISORWERPRODRO2.pfx',
    PASSWORD = 'Password123',
    CERT_DETAILS = 'C:\MISO\certs\MISORWERPRODRO2.pfx'
WHERE ASSET_OWNER_KEY = (
    SELECT so.ASSET_OWNER_KEY
    FROM SASSET_OWNER so
    INNER JOIN SISO_PORTFOLIO_MAPPING spm
        ON so.ISO_PORTFOLIO_MAPPING_KEY = spm.ISO_PORTFOLIO_MAPPING_KEY
    WHERE so.NAME = 'RWER'
    AND spm.NAME = 'MISO'
);

UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\LowEnvPTWF2.pfx',
    PASSWORD = 'Password123',
    CERT_DETAILS = 'C:\MISO\certs\LowEnvPTWF2.pfx'
WHERE ASSET_OWNER_KEY = (
    SELECT so.ASSET_OWNER_KEY
    FROM SASSET_OWNER so
    INNER JOIN SISO_PORTFOLIO_MAPPING spm
        ON so.ISO_PORTFOLIO_MAPPING_KEY = spm.ISO_PORTFOLIO_MAPPING_KEY
    WHERE so.NAME = 'PTWF'
    AND spm.NAME = 'MISO'
);

UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\LowEnvSTWF2.pfx',
    PASSWORD = 'Password123',
    CERT_DETAILS = 'C:\MISO\certs\LowEnvSTWF2.pfx'
WHERE ASSET_OWNER_KEY = (
    SELECT so.ASSET_OWNER_KEY
    FROM SASSET_OWNER so
    INNER JOIN SISO_PORTFOLIO_MAPPING spm
        ON so.ISO_PORTFOLIO_MAPPING_KEY = spm.ISO_PORTFOLIO_MAPPING_KEY
    WHERE so.NAME = 'STWF'
    AND spm.NAME = 'MISO'
);

UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'QRTZ',
        'RWER'
    )
);

UPDATE SLOV_VALUE
SET
    PROPERTY1 = 'C:\MISO\certs\LowEnvPTWF2.pfx',
    PROPERTY2 = 'Password123'
WHERE LOV_KEY = (SELECT LOV_KEY FROM SLOV WHERE NAME = 'MISO CROW Market Participant Info') AND DISPLAY = 'PTWF';

UPDATE SLOV_VALUE
SET
    PROPERTY1 = 'C:\MISO\certs\LowEnvSTWF2.pfx',
    PROPERTY2 = 'Password123'
WHERE LOV_KEY = (SELECT LOV_KEY FROM SLOV WHERE NAME = 'MISO CROW Market Participant Info') AND DISPLAY = 'STWF';