UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\PCIXCELMISORO_NSPP.pfx',
    PASSWORD = 'Spiupo25!',
    CERT_DETAILS = 'C:\MISO\certs\PCIXCELMISORO_NSPP.pfx'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'NSPP',
        'NSPT',
        'NULM',
        'SHERCO3'
    )
);

UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\PCIXCELMISORO_PSCM.pfx',
    PASSWORD = 'Spiupo24!',
    CERT_DETAILS = 'C:\MISO\certs\PCIXCELMISORO_PSCM.pfx'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'PSCM');

UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\PCIXCELMISORO_PSCP.pfx',
    PASSWORD = 'Spiupo24!',
    CERT_DETAILS = 'C:\MISO\certs\PCIXCELMISORO_PSCP.pfx'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'PSCP');

UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\PCIXCELMISORO_SPSM.pfx',
    PASSWORD = 'Spiupo24!',
    CERT_DETAILS = 'C:\MISO\certs\PCIXCELMISORO_SPSM.pfx'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'SPSM');

UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'C:\MISO\certs\PCIXCELMISORO_SPSP.pfx',
    PASSWORD = 'Spiupo24!',
    CERT_DETAILS = 'C:\MISO\certs\PCIXCELMISORO_SPSP.pfx'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'SPSP');

-- NSPP has no access to the MARKETS portal
UPDATE SPARAMETER SET VALUE = 'T' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_MISO_' and NAME = 'MISO_DART2_HOST_TARGET_DOWNLOADS';

-- Other AOs have no access to either the CCE or MARKETS portals   
UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'N',
    SETTLE = 'N'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'NSPT',
        'NULM',
        'SHERCO3',
        'PSCM',
        'PSCP',
        'SPSM',
        'SPSP'
    )
);