DECLARE 
tmp1 varchar2(100);
tmp2 varchar2(100);
BEGIN
	UPDATE SUSER SET U_PASSWORD = 'gtwp$pci1' WHERE U_NAME IN ('Admin','background');
	UPDATE SPARAMETER SET "VALUE" = 'gtwp$pci1' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'BACKGROUND_PASSWORD';
	
	UPDATE SLOV_VALUE SET PROPERTY1 = 'C:\CAISO\CAISOEIM.keystore', PROPERTY2 = 'caisoteam', PROPERTY4 = 'caisoteam' WHERE LOV_KEY = (SELECT LOV_KEY FROM SLOV WHERE NAME = 'CAISO OMS Market Participant Info');
	UPDATE SLOV_VALUE SET PROPERTY1 = 'false' WHERE LOV_KEY = (SELECT LOV_KEY FROM SLOV WHERE NAME = 'CAISO ISO Comm Task Redirect');
	
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Archive' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'ARCHIVE_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Auto_Upload' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'AUTO_UPLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Download' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'DOWNLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Settlements\Download' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'INVOICE_LOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Bid_Status' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'MERCHANT_TO_ENTITY_SHARE';
	UPDATE SPARAMETER SET VALUE = 'T' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'OMS_MODE';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\CAISOEIM.keystore' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'OMS_TRUSTSTORE';
	UPDATE SPARAMETER SET VALUE = 'caisoteam' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'OMS_TRUSTSTOREPASSWORD';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Settlements\Archive' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'SETTLEMENT_ARCHIVE_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Settlements\Download' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'SETTLEMENT_DOWNLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Settlements\Historic' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'SETTLEMENT_HISTORIC_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Settlements\Upload' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'STATEMENT_LOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\CAISOEIM.keystore' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'TRUST_STORE';
	UPDATE SPARAMETER SET VALUE = 'caisoteam' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'TRUST_STORE_PASSWORD';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Upload' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'UPLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'N' WHERE SYSTEM = 'GenManager' and TYPE = 'CAISO' and NAME = 'USE_MODE';

	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Import_Datafeed\Import_Files\Load_Forecast\Archive' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'ARCHIVE_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Import_Datafeed\ETL_Export_Latest' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'ETL_EXPORT_LATEST';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Exports' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'EXPORT_FILES';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Import_Datafeed\Import_Files' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'IMPORT_FILES';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Import_Datafeed\IT_Datafeed_Files' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'IT_DATAFEED_FILES';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Import_Datafeed\IT_Datafeed_Files\WACOG' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'IT_DATAFEED_FILES_WACOG';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Bid_Status' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'M_TO_E';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Exports' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'OBJ_STORE_PATH';
	UPDATE SPARAMETER SET VALUE = 'C:\CAISO\Exports' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'RTP.OBJ_STORE_PATH';

	UPDATE SPARAMETER SET VALUE = 'PCI Cloud Environment' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'ENVIRONMENT';
	UPDATE SPARAMETER SET VALUE = '<a href="../../common/portal.jsp"><img id="logo-img" src="/images/logo-white-on-clear-bg.svg"/></a>' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'PORTAL_LOGO';
	UPDATE SPARAMETER SET VALUE = '<a href="../../common/portal.jsp"><img id="logo-img" src="/images/logo-white-on-clear-bg.svg"/></a>' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'PORTAL_LOGO_DARK';

	UPDATE SPARAMETER SET VALUE = 'gsms' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'GP_CONNECT';
	UPDATE SPARAMETER SET VALUE = 'pci' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'GP_PASSWORD';
	UPDATE SPARAMETER SET VALUE = 'pci' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'GP_USER';
	UPDATE SPARAMETER SET VALUE = 'false' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'FILE_ARCHIVER_ENABLED';

	UPDATE SPARAMETER SET VALUE = 'true' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'STORE_BID_RESULT_DATA';
	UPDATE SPARAMETER SET VALUE = 'C:\ISO\STORE_BID_RESULT_DATA' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'STORE_BID_RESULT_DATA_DIR';
	UPDATE SPARAMETER SET VALUE = 'true' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'STORE_BID_SUBMIT_DATA';
	UPDATE SPARAMETER SET VALUE = 'C:\ISO\STORE_BID_SUBMIT_DATA' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'STORE_BID_SUBMIT_DATA_DIR';
	UPDATE SPARAMETER SET VALUE = 'true' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'STORE_CB_BID_DATA';

	DELETE FROM SPARAMETER WHERE NAME = 'AUTO_QUERY_BID_RESULTS_RT';
	BEGIN 
		SELECT VALUE INTO tmp1 FROM sparameter WHERE NAME='STORE_BID_RESULT_DATA'; 
	EXCEPTION
		WHEN no_data_found THEN
		INSERT INTO SPARAMETER (PARAMETER_KEY, NAME, VALUE, DESCRIPTION, SYSTEM, TYPE, MODIFIEDON, MODIFIEDBY, CREATEDON, CREATEDBY) VALUES ((SELECT MAX(PARAMETER_KEY)+1 FROM SPARAMETER), 'STORE_BID_RESULT_DATA', 'true', '','GenManager', 'ISO', '10-JAN-18 11.05.04.000000000 PM', 'background', '10-JAN-18 11.05.04.000000000 PM', 'background');
	END; 
	BEGIN 
		SELECT VALUE INTO tmp2 FROM sparameter WHERE NAME='STORE_BID_RESULT_DATA_DIR'; 
	EXCEPTION
		WHEN no_data_found THEN
		INSERT INTO SPARAMETER (PARAMETER_KEY, NAME, VALUE, DESCRIPTION, SYSTEM, TYPE, MODIFIEDON, MODIFIEDBY, CREATEDON, CREATEDBY) VALUES ((SELECT MAX(PARAMETER_KEY)+1 FROM SPARAMETER), 'STORE_BID_RESULT_DATA_DIR', 'C:\ISO\STORE_BID_RESULT_DATA', '','GenManager', 'ISO', '10-JAN-18 11.05.04.000000000 PM', 'background', '10-JAN-18 11.05.04.000000000 PM', 'background');
	END; 
	UPDATE SSYS_ID SET NEXT_KEY = (SELECT MAX(PARAMETER_KEY) FROM SPARAMETER) WHERE ID_TYPE = 'PARAMETER';
	COMMIT;
END;