UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci eesc test user1x18157 (caiso_issuing_ca)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI EESC TEST USER1x18157,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'AVAM');
UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci eesc test user1x18157 (caiso_issuing_ca)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI EESC TEST USER1x18157,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'AVAT');
UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci eesc test user1x18157 (caiso_issuing_ca)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI EESC TEST USER1x18157,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'AVISTA');


UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\SFTP_CERTS\CAISO-Settlements\AVISTA\avwppcitestbo' WHERE NAME = 'AVWP_CERT';