UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\SFTP_CERTS\CAISO-Settlements\TID\insertkeyname' WHERE NAME = 'insertassetownername';

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci mapstage_stagex16039 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI MAPSTAGE_STAGEx16039,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'TIDC');

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci mapstage_stagex16039 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI MAPSTAGE_STAGEx16039,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'TIDC_BA');

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci mapstage_stagex16039 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI MAPSTAGE_STAGEx16039,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'TIDP');

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci mapstage_stagex16039 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI MAPSTAGE_STAGEx16039,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'TIDR');

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci eesc mapstage_stagex16207 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI EESC MAPSTAGE_STAGEx16207,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'TIDE');