UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\SFTP_CERTS\CAISO-Settlements\TPU-MT\TPU_BO_Private.ppk' WHERE NAME = 'TCM1_CERT';

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci testx14350 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI TESTx14350,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'TCM1');

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci tpwe-bo-testx18484 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI TPWE-BO-TESTx18484, OU=people, O=CAISO, C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'TPWE');

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci tpwe-bo-testx18484 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI TPWE-BO-TESTx18484, OU=people, O=CAISO, C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'TPWM');

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci tpwe-bo-testx18484 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI TPWE-BO-TESTx18484, OU=people, O=CAISO, C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'TPWR_BA');