UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci scid-testx20906 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI SCID-TESTx20906,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'EXC_PACE_2116');

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci scid-testx20906 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI SCID-TESTx20906,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'EXC_PACE_2156');

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci scid-testx20906 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI SCID-TESTx20906,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'PACE');

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci scid-testx20906 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI SCID-TESTx20906,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'UMPA');

UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci scid-testx20906 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI SCID-TESTx20906,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'UTPR');

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\SFTP_CERTS\CAISO-Settlements\UMPA-MT\UMPA_Private.ppk' WHERE NAME = 'UMPA_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\SFTP_CERTS\CAISO-Settlements\UMPA-MT\UMPA_Private.ppk' WHERE NAME = 'UTPR_CERT';