UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci caiso testx9775 (caiso_issuing_ca)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI CAISO TESTx9775,OU=people,O=CAISO,C=US' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'PSCB');

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\SFTP_CERTS\CAISO-Settlements\XCEL\Prodprivatekey.ppk' WHERE NAME = 'PSCB_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\SFTP_CERTS\CAISO-Settlements\XCEL\Prodprivatekey.ppk' WHERE NAME = 'XCEL_PROD_CERT';