UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y',
	CERTIFICATE = 'C:\ISONE\Certificates\isone_test_rw.pfx',
    PASSWORD = 'PCItestkey2026!'
WHERE ASSET_OWNER_KEY = (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'IGSINC'
);

-- UPDATE SASSET_OWNER_CONFIG
-- SET 
--     ACTIVE = 'Y',
-- 	CERTIFICATE = 'C:\ISONE\Certificates\isone_prod_ro.pfx',
--     PASSWORD = 'PCIprodkey2026!'
-- WHERE ASSET_OWNER_KEY = (
--     SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
--     WHERE NAME = 'IGSINC'
-- );