UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y',
	CERTIFICATE = 'C:\ISONE\Certificates\RWE ISONE RO_09022025.pfx',
    PASSWORD = '123',
-- SFTP_USER
    USER1 = 'S600073355',
-- SFTP_PASSWORD
    USER2 = 'opyi0mrk'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'Cassadaga'
);

UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y',
	CERTIFICATE = 'C:\ISONE\Certificates\RWE ISONE RO_09022025.pfx',
    PASSWORD = '123',
-- SFTP_USER
    USER1 = 'PCIuser123',
-- SFTP_PASSWORD
    USER2 = 'u6BS:Sy'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'RWECE'
);