BEGIN
 	UPDATE SUSER SET U_PASSWORD = 'gtwp$pci1' WHERE U_NAME IN ('Admin','background');
	UPDATE SPARAMETER SET "VALUE" = 'gtwp$pci1' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'BACKGROUND_PASSWORD';
  
	UPDATE SUSER SET SOURCE = 'S';
	UPDATE SASSET_OWNER_CONFIG SET ACTIVE= 'N';

	UPDATE SPARAMETER SET VALUE = 'https://ssotrain.pjm.com/access/authenticate/pjmauthcert' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'DR_HUB_SANDBOX_AUTH_HOST';
	UPDATE SPARAMETER SET VALUE = 'https://ssotrain.pjm.com/access/authenticate/pjmauthcert' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'EX_SCHEDULE_SANDBOX_AUTH_HOST';
	UPDATE SPARAMETER SET VALUE = 'https://ssotrain.pjm.com/access/authenticate/pjmauthcert' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'FTR_CENTER_SANDBOX_AUTH_HOST';
	UPDATE SPARAMETER SET VALUE = 'https://ssotrain.pjm.com/access/authenticate/pjmauthcert' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'IN_SCHEDULE_SANDBOX_AUTH_HOST';
	UPDATE SPARAMETER SET VALUE = 'https://ssotrain.pjm.com/access/authenticate/pjmauthcert' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'MARKETS_GATEWAY_SANDBOX_AUTH_HOST';
	UPDATE SPARAMETER SET VALUE = 'https://ssotrain.pjm.com/access/authenticate/pjmauthcert' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'MSRS_SANDBOX_AUTH_HOST';
	UPDATE SPARAMETER SET VALUE = 'https://ssotrain.pjm.com/access/authenticate/pjmauthcert' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'POWER_METER_SANDBOX_AUTH_HOST';

	UPDATE SPARAMETER SET VALUE = 'P' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'DATA_MINER_MODE';
	UPDATE SPARAMETER SET VALUE = 'P' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'DR_HUB_MODE';
	UPDATE SPARAMETER SET VALUE = 'P' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'EX_SCHEDULE_MODE';
	UPDATE SPARAMETER SET VALUE = 'P' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'FTR_MODE';
	UPDATE SPARAMETER SET VALUE = 'P' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'MARKETS_GATEWAY_REST_MODE';
	UPDATE SPARAMETER SET VALUE = 'P' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'MSRS_MODE';
	UPDATE SPARAMETER SET VALUE = 'P' WHERE SYSTEM = 'ISOCOMM' and TYPE = '_PJM_' and NAME = 'POWER_METER_MODE';
	UPDATE SPARAMETER SET VALUE = 'P' WHERE SYSTEM = 'GenManager' and TYPE = '_SYSTEM_' and NAME = 'IN_SCHEDULE_MODE';

	UPDATE SPARAMETER SET VALUE = 'C:\PJM\download' WHERE SYSTEM = 'GenManager' and TYPE = '_SYSTEM_' and NAME = 'DOWNLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\Settlements\statements' WHERE SYSTEM = 'GenManager' and TYPE = '_SYSTEM_' and NAME = 'SETTLEMENT_STATEMENTS';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\upload' WHERE SYSTEM = 'GenManager' and TYPE = '_SYSTEM_' and NAME = 'UPLOAD_DIRECTORY';

	UPDATE SPARAMETER SET VALUE = 'C:\PJM\download2' WHERE SYSTEM = 'GenManager' and TYPE = '_PJM_' and NAME = 'DOWNLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\archive' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'ARCHIVE_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\auto' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'AUTO_UPLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\Settlements\download' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'DOWNLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\invoices\invoiceDownload' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'INVOICE_LOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\Settlements\archive' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'SETTLEMENT_ARCHIVE_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\Settlements\download2' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'SETTLEMENT_DOWNLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\invoices\pdfDisplay' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'SETTLEMENT_INVOICE_PDF_DISPLAY_DIR';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\invoices\pdfDownload' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'SETTLEMENT_INVOICE_PDF_DOWNLOAD_DIR';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\Settlements\statementLoad' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'STATEMENT_LOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\PCIKEY.Keystore' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'TRUST_STORE';
	UPDATE SPARAMETER SET VALUE = 'C:\PJM\uploadAuto' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'UPLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'tQJPeerA' WHERE SYSTEM = 'GenManager' and TYPE = 'PJM' and NAME = 'TRUST_STORE_PASSWORD';

	UPDATE SPARAMETER SET VALUE = 'Y' WHERE SYSTEM = 'GenManager' and TYPE = '_SYSTEM_' and NAME = 'EDART_SANDBOX';
	UPDATE SPARAMETER SET VALUE = '-' WHERE SYSTEM = 'AssetOperations' and TYPE = 'OutageManagementPJM' and NAME = 'EDART_URL_S';
	UPDATE SPARAMETER SET VALUE = '-' WHERE SYSTEM = 'AssetOperations' and TYPE = 'OutageManagementPJM' and NAME = 'USE_MODE';

	UPDATE SPARAMETER SET VALUE = 'PCI Cloud Environment' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'ENVIRONMENT';
	UPDATE SPARAMETER SET VALUE = '<a href="../../common/portal.jsp"><img id="logo-img" src="/images/logo-white-on-clear-bg.svg"/></a>' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'PORTAL_LOGO';
	UPDATE SPARAMETER SET VALUE = '<a href="../../common/portal.jsp"><img id="logo-img" src="/images/logo-white-on-clear-bg.svg"/></a>' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'PORTAL_LOGO_DARK';

	UPDATE SPARAMETER SET VALUE = 'gsms' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'GP_CONNECT';
	UPDATE SPARAMETER SET VALUE = 'pci' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'GP_PASSWORD';
	UPDATE SPARAMETER SET VALUE = 'pci' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'GP_USER';
	UPDATE SPARAMETER SET VALUE = 'false' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'FILE_ARCHIVER_ENABLED';
  COMMIT;
END;