UPDATE SASSET_OWNER_CONFIG
SET
    ACTIVE = 'Y',
    SETTLE = 'Y',
    CERTIFICATE = 'pci mote rw qecnr',
    PASSWORD = 'changeit',
    CERT_DETAILS = 'C:\ERCOT\FO\Certificates\MOTE\deploy_qecnr.wsdd'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'QECNR');

UPDATE SASSET_OWNER_CONFIG
SET
    ACTIVE = 'Y',
    SETTLE = 'Y',
    CERTIFICATE = 'pci mote rw qecnr2',
    PASSWORD = 'changeit',
    CERT_DETAILS = 'C:\ERCOT\FO\Certificates\MOTE\deploy_qecnr2.wsdd'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'QECNR2');

UPDATE SASSET_OWNER_CONFIG
SET
    ACTIVE = 'Y',
    SETTLE = 'Y',
    CERTIFICATE = 'pci mote ro qecnr3',
    PASSWORD = 'changeit',
    CERT_DETAILS = 'C:\ERCOT\FO\Certificates\MOTE\deploy_qecnr3.wsdd'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'QECNR3');

UPDATE SASSET_OWNER_CONFIG
SET
    ACTIVE = 'Y',
    SETTLE = 'Y',
    CERTIFICATE = 'pci mote rw qecnr4',
    PASSWORD = 'changeit',
    CERT_DETAILS = 'C:\ERCOT\FO\Certificates\MOTE\deploy_qecnr4.wsdd'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'QECNR4');

UPDATE SASSET_OWNER_CONFIG
SET
    ACTIVE = 'Y',
    SETTLE = 'Y',
    CERTIFICATE = 'pci mote rw qecnr5',
    PASSWORD = 'changeit',
    CERT_DETAILS = 'C:\ERCOT\FO\Certificates\MOTE\deploy_qecnr5.wsdd'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'QECNR5');

UPDATE SASSET_OWNER_CONFIG
SET
    ACTIVE = 'Y',
    SETTLE = 'Y',
    CERTIFICATE = 'pci mote rw qecnr6',
    PASSWORD = 'changeit',
    CERT_DETAILS = 'C:\ERCOT\FO\Certificates\MOTE\deploy_qecnr6.wsdd'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'QECNR6');

UPDATE SASSET_OWNER_CONFIG
SET
    ACTIVE = 'Y',
    SETTLE = 'Y',
    CERTIFICATE = 'pci mote rw qecnr7',
    PASSWORD = 'changeit',
    CERT_DETAILS = 'C:\ERCOT\FO\Certificates\MOTE\deploy_qecnr7.wsdd'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'QECNR7');

-- No MOTE cert available: XECNR1, XECNR2 stay deactivated (generic SQL default)
