UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'C:\MISO\certs\RWE\CERT-1734\MISORWERPRODRO2.pfx', PASSWORD = 'Password123', CERT_DETAILS = 'C:\MISO\certs\RWE\CERT-1734\MISORWERPRODRO2.pfx' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'CFSF');
UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'C:\MISO\certs\RWE\CERT-1734\MISORWERPRODRO2.pfx', PASSWORD = 'Password123', CERT_DETAILS = 'C:\MISO\certs\RWE\CERT-1734\MISORWERPRODRO2.pfx' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'EMSF');
UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'C:\MISO\certs\RWE\CERT-1734\MISORWERPRODRO2.pfx', PASSWORD = 'Password123', CERT_DETAILS = 'C:\MISO\certs\RWE\CERT-1734\MISORWERPRODRO2.pfx' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'LFSF');
UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'C:\MISO\certs\RWE\CERT-1734\MISORWERPRODRO2.pfx', PASSWORD = 'Password123', CERT_DETAILS = 'C:\MISO\certs\RWE\CERT-1734\MISORWERPRODRO2.pfx' WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY from SASSET_OWNER WHERE NAME = 'QRTZ');
UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'C:\MISO\certs\RWE\CERT-1698\LowEnvPTWF2.pfx', PASSWORD = 'Password123', CERT_DETAILS = 'C:\MISO\certs\RWE\CERT-1698\LowEnvPTWF2.pfx' WHERE ASSET_OWNER_KEY = (
    SELECT so.ASSET_OWNER_KEY
    from SASSET_OWNER so
    INNER JOIN SISO_PORTFOLIO_MAPPING spm
        ON so.ISO_PORTFOLIO_MAPPING_KEY = spm.ISO_PORTFOLIO_MAPPING_KEY
    WHERE so.NAME = 'PTWF' 
    AND spm.NAME = 'MISO'
);
UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'C:\MISO\certs\RWE\CERT-1698\LowEnvPTWF2.pfx', PASSWORD = 'Password123', CERT_DETAILS = 'C:\MISO\certs\RWE\CERT-1698\LowEnvPTWF2.pfx' WHERE ASSET_OWNER_KEY = (
    SELECT so.ASSET_OWNER_KEY
    from SASSET_OWNER so
    INNER JOIN SISO_PORTFOLIO_MAPPING spm
        ON so.ISO_PORTFOLIO_MAPPING_KEY = spm.ISO_PORTFOLIO_MAPPING_KEY
    WHERE so.NAME = 'RWER' 
    AND spm.NAME = 'MISO'
);
UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'C:\MISO\certs\RWE\CERT-1698\LowEnvPTWF2.pfx', PASSWORD = 'Password123', CERT_DETAILS = 'C:\MISO\certs\RWE\CERT-1698\LowEnvPTWF2.pfx' WHERE ASSET_OWNER_KEY = (
    SELECT so.ASSET_OWNER_KEY
    from SASSET_OWNER so
    INNER JOIN SISO_PORTFOLIO_MAPPING spm
        ON so.ISO_PORTFOLIO_MAPPING_KEY = spm.ISO_PORTFOLIO_MAPPING_KEY
    WHERE so.NAME = 'STWF' 
    AND spm.NAME = 'MISO'
);