UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y',
	CERTIFICATE = 'PCI_qa',
    PASSWORD = 'M0C!2018^tRAn',
-- PKI_CERTIFICATE_PATH
    USER15 = 'C:\PCI\certificates\pki\PCI-EKPC-PJM-PROD-RO.p12',
-- PKI_CERTIFICATE_PASSWORD
    USER16 = 'EKPC_pjm_PK1!',
-- PKI_CERTIFICATE_PATH_SANDBOX
    USER17 = 'C:\PCI\certificates\pki\PCI-EKPC-PJM-SAND-RW.p12',
-- PKI_CERTIFICATE_PASSWORD_SANDBOX
    USER18 = 'EKPC_pjm_PK1!',
-- SANDBOX_USERNAME
    USER19 = 'PCIsand',
-- SANDBOX_PASSWORD
    USER20 = 'M0C?2018$Gen'
WHERE ASSET_OWNER_KEY = (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'EKPC'
);