UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y',
	CERTIFICATE = 'PCICEDSOL',
    PASSWORD = 'Password1!',
-- PKI_CERTIFICATE_PATH
    USER15 = 'C:\PCI\certificates\pki\PCICEDSOL2.pfx',
-- PKI_CERTIFICATE_PASSWORD
    USER16 = 'Password123',
-- PKI_CERTIFICATE_PATH_SANDBOX
    USER17 = 'C:\PCI\certificates\pki\',
-- PKI_CERTIFICATE_PASSWORD_SANDBOX
    USER18 = '',
-- SANDBOX_USERNAME
    USER19 = 'PCICEDSOLT',
-- SANDBOX_PASSWORD
    USER20 = 'Password1!'
WHERE ASSET_OWNER_KEY = (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'CEDSOL'
);

UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y',
	CERTIFICATE = 'PCI_S_SR',
    PASSWORD = '20$PciOct01',
-- PKI_CERTIFICATE_PATH
    USER15 = 'C:\PCI\certificates\pki\PCIPJMPRODSCIOTORO.pfx',
-- PKI_CERTIFICATE_PASSWORD
    USER16 = 'Password123',
-- PKI_CERTIFICATE_PATH_SANDBOX
    USER17 = 'C:\PCI\certificates\pki\HARDPCITEST3.pfx',
-- PKI_CERTIFICATE_PASSWORD_SANDBOX
    USER18 = 'Password123!',
-- SANDBOX_USERNAME
    USER19 = 'PCI_S_SR',
-- SANDBOX_PASSWORD
    USER20 = '23$PciMar16'
WHERE ASSET_OWNER_KEY = (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'HARWIN'
);

-- CCRadRun: Invalid credentials
-- CCRadRunPCI: Invalid credentials
UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'N',
	CERTIFICATE = 'CCRadRun',
    PASSWORD = '25$PciFeb17',
-- PKI_CERTIFICATE_PATH
    USER15 = 'C:\PCI\certificates\pki\PCIPJMPRODRRUNRO.pfx',
-- PKI_CERTIFICATE_PASSWORD
    USER16 = 'Password123',
-- PKI_CERTIFICATE_PATH_SANDBOX
    USER17 = 'C:\PCI\certificates\pki\PJMTRAINPCI3 12182025.pfx',
-- PKI_CERTIFICATE_PASSWORD_SANDBOX
    USER18 = 'Password123',
-- SANDBOX_USERNAME
    USER19 = 'CCRadRunPCI',
-- SANDBOX_PASSWORD
    USER20 = '26$PciFeb09'
WHERE ASSET_OWNER_KEY = (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'RADFWF'
);

-- PCIQSEPRODRO: Invalid credentials
UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'N',
	CERTIFICATE = 'PCIQSEPRODRO',
    PASSWORD = '25$PciMar13',
-- PKI_CERTIFICATE_PATH
    USER15 = 'C:\PCI\certificates\pki\PCIQSEPRODRO.pfx',
-- PKI_CERTIFICATE_PASSWORD
    USER16 = 'Password123',
-- PKI_CERTIFICATE_PATH_SANDBOX
    USER17 = 'C:\PCI\certificates\pki\PCITESTQSERW.pfx',
-- PKI_CERTIFICATE_PASSWORD_SANDBOX
    USER18 = 'Password123',
-- SANDBOX_USERNAME
    USER19 = 'PCIQSETESTRW',
-- SANDBOX_PASSWORD
    USER20 = '25$PciMar13'
WHERE ASSET_OWNER_KEY = (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'RWEQSE'
);

-- CCStonyCr: Invalid credentials
UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'N',
	CERTIFICATE = 'CCStonyCr',
    PASSWORD = '25$TrainMar14',
-- PKI_CERTIFICATE_PATH
    USER15 = 'C:\PCI\certificates\pki\PCIPJMPRODSTONYRO.pfx',
-- PKI_CERTIFICATE_PASSWORD
    USER16 = 'Password123',
-- PKI_CERTIFICATE_PATH_SANDBOX
    USER17 = 'C:\PCI\certificates\pki\SCrkPCITEST3.pfx',
-- PKI_CERTIFICATE_PASSWORD_SANDBOX
    USER18 = 'Password123!',
-- SANDBOX_USERNAME
    USER19 = 'StonyCCEPCI',
-- SANDBOX_PASSWORD
    USER20 = '26$PciFeb09'
WHERE ASSET_OWNER_KEY = (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'SCWF'
);

UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y',
	CERTIFICATE = 'PCIURidgeRO',
    PASSWORD = 'Password123!',
-- PKI_CERTIFICATE_PATH
    USER15 = 'C:\PCI\certificates\pki\PCIUnionRidgeRO.pfx',
-- PKI_CERTIFICATE_PASSWORD
    USER16 = 'Password123',
-- PKI_CERTIFICATE_PATH_SANDBOX
    USER17 = 'C:\PCI\certificates\pki\',
-- PKI_CERTIFICATE_PASSWORD_SANDBOX
    USER18 = '',
-- SANDBOX_USERNAME
    USER19 = '',
-- SANDBOX_PASSWORD
    USER20 = ''
WHERE ASSET_OWNER_KEY = (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'URSF'
);


UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y',
	CERTIFICATE = 'PCI_RO_WB',
    PASSWORD = 'Password1!',
-- PKI_CERTIFICATE_PATH
    USER15 = 'C:\PCI\certificates\pki\WillowbrookProdROTest2.pfx',
-- PKI_CERTIFICATE_PASSWORD
    USER16 = 'Password123',
-- PKI_CERTIFICATE_PATH_SANDBOX
    USER17 = 'C:\PCI\certificates\pki\WBROOKTEST2.pfx',
-- PKI_CERTIFICATE_PASSWORD_SANDBOX
    USER18 = 'Password123!',
-- SANDBOX_USERNAME
    USER19 = 'PCI_TRAIN_WB',
-- SANDBOX_PASSWORD
    USER20 = 'Password1!'
WHERE ASSET_OWNER_KEY = (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'WILBRK'
);

-- CCwildcatAEP: Invalid credentials
UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'N',
	CERTIFICATE = 'CCwildcatAEP',
    PASSWORD = '25$PciJun11',
-- PKI_CERTIFICATE_PATH
    USER15 = 'C:\PCI\certificates\pki\PCIPJMPRODWCAEPRO.pfx',
-- PKI_CERTIFICATE_PASSWORD
    USER16 = 'Password123',
-- PKI_CERTIFICATE_PATH_SANDBOX
    USER17 = 'C:\PCI\certificates\pki\WCATAEPTEST3.pfx',
-- PKI_CERTIFICATE_PASSWORD_SANDBOX
    USER18 = 'Password123!',
-- SANDBOX_USERNAME
    USER19 = 'WLDAEPTstPCI',
-- SANDBOX_PASSWORD
    USER20 = '26$PciFeb12'
WHERE ASSET_OWNER_KEY = (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'WLDAEP'
);

-- CCwildcatEON: Invalid credentials
UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'N',
	CERTIFICATE = 'CCwildcatEON',
    PASSWORD = '24$PciOct14',
-- PKI_CERTIFICATE_PATH
    USER15 = 'C:\PCI\certificates\pki\PCIPJMPRODWCRWERO.pfx',
-- PKI_CERTIFICATE_PASSWORD
    USER16 = 'Password123',
-- PKI_CERTIFICATE_PATH_SANDBOX
    USER17 = 'C:\PCI\certificates\pki\WCATPCITEST3.pfx',
-- PKI_CERTIFICATE_PASSWORD_SANDBOX
    USER18 = 'Password123!',
-- SANDBOX_USERNAME
    USER19 = 'WLDWF1TstPCI',
-- SANDBOX_PASSWORD
    USER20 = '26$PciFeb09'
WHERE ASSET_OWNER_KEY = (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'WLDWF1'
);