DECLARE 
tmp1 varchar2(100);
tmp2 varchar2(100);
BEGIN
	UPDATE SUSER SET U_PASSWORD = 'gtwp$pci1' WHERE U_NAME IN ('Admin','background');
	UPDATE SPARAMETER SET "VALUE" = 'gtwp$pci1' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'BACKGROUND_PASSWORD';

	UPDATE SASSET_OWNER_CONFIG SET ACTIVE = 'N', SETTLE = 'N';

	UPDATE SPARAMETER SET VALUE = 'C:\PCI\archive' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'ARCHIVE_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\upload\auto' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'AUTO_UPLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\certificates' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'CERTS_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'S' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'CROW_MODE';
	UPDATE SPARAMETER SET VALUE = 'https://api-mte.itespp.org/OutageManagementService' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'CROW_URL_S';
	UPDATE SPARAMETER SET VALUE = 'https://api-mte.itespp.org/OutageManagementService' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'CROW_URL_T';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\download' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'DOWNLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\archive' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'SETTLEMENT_ARCHIVE_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\statements' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'STATEMENT_LOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\certificates\sppim_2017.JKS' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'TRUST_STORE';
	UPDATE SPARAMETER SET VALUE = 'changeit' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'TRUST_STORE_PASSWORD';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\upload' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'UPLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'A' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPIM' and NAME = 'USE_MODE';

	UPDATE SPARAMETER SET VALUE = 'C:\PCI\archive' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPTS' and NAME = 'ARCHIVE_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\certificates' WHERE SYSTEM ='GenManager' and TYPE = 'SPPTS' and NAME = 'CERTS_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\download' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPTS'  and NAME = 'DOWNLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\archive' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPTS' and NAME = 'SETTLEMENT_ARCHIVE_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\statements' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPTS' and NAME = 'STATEMENT_LOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\test' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPTS' and NAME = 'TEST_FILES_LOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\certificates\sppim_2017.JKS' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPTS' and NAME = 'TRUST_STORE';
	UPDATE SPARAMETER SET VALUE = 'changeit' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPTS' and NAME = 'TRUST_STORE_PASSWORD';
	UPDATE SPARAMETER SET VALUE = 'C:\PCI\upload' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPTS' and NAME = 'UPLOAD_DIRECTORY';
	UPDATE SPARAMETER SET VALUE = 'A' WHERE SYSTEM = 'GenManager' and TYPE = 'SPPTS' and NAME = 'USE_MODE';

	UPDATE SPARAMETER SET VALUE = 'C:\iso_messages\archive' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'CACHER_ARCHIVE_ROOT_DIR';
	UPDATE SPARAMETER SET VALUE = 'C:\iso_messages' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'CACHER_ROOT_PATH';
	UPDATE SPARAMETER SET VALUE = 'sppim' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'CACHER_ISO_PATH';
	UPDATE SPARAMETER SET VALUE = 'Prod' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'CACHER_SERVER_PATH';
	UPDATE SPARAMETER SET VALUE = 'Admin' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'USER_NAME';
	UPDATE SPARAMETER SET VALUE = 'gtwp' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'USER_PASSWORD';

	UPDATE SPARAMETER SET VALUE = 'PCI Cloud Environment' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'ENVIRONMENT';
	UPDATE SPARAMETER SET VALUE = '<a href="../../common/portal.jsp"><img id="logo-img" src="/images/logo-white-on-clear-bg.svg"/></a>' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'PORTAL_LOGO';
	UPDATE SPARAMETER SET VALUE = '<a href="../../common/portal.jsp"><img id="logo-img" src="/images/logo-white-on-clear-bg.svg"/></a>' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'PORTAL_LOGO_DARK';

	UPDATE SPARAMETER SET VALUE = 'gsms' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'GP_CONNECT';
	UPDATE SPARAMETER SET VALUE = 'pci' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'GP_PASSWORD';
	UPDATE SPARAMETER SET VALUE = 'pci' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'GP_USER';
	UPDATE SPARAMETER SET VALUE = 'false' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'FILE_ARCHIVER_ENABLED';

	UPDATE SPARAMETER SET VALUE = 'true' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'STORE_BID_RESULT_DATA';
	UPDATE SPARAMETER SET VALUE = 'C:\ISO\STORE_BID_RESULT_DATA' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'STORE_BID_RESULT_DATA_DIR';
	UPDATE SPARAMETER SET VALUE = 'true' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'STORE_BID_SUBMIT_DATA';
	UPDATE SPARAMETER SET VALUE = 'C:\ISO\STORE_BID_SUBMIT_DATA' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'STORE_BID_SUBMIT_DATA_DIR';
	UPDATE SPARAMETER SET VALUE = 'true' WHERE SYSTEM = 'GenManager' and TYPE = 'ISO' and NAME = 'STORE_CB_BID_DATA';

	DELETE FROM SPARAMETER WHERE NAME = 'AUTO_QUERY_BID_RESULTS_RT';
	BEGIN 
		SELECT VALUE INTO tmp1 FROM sparameter WHERE NAME='STORE_BID_RESULT_DATA'; 
	EXCEPTION
		WHEN no_data_found THEN
		INSERT INTO SPARAMETER (PARAMETER_KEY, NAME, VALUE, DESCRIPTION, SYSTEM, TYPE, MODIFIEDON, MODIFIEDBY, CREATEDON, CREATEDBY) VALUES ((SELECT MAX(PARAMETER_KEY)+1 FROM SPARAMETER), 'STORE_BID_RESULT_DATA', 'true', '','GenManager', 'ISO', '10-JAN-18 11.05.04.000000000 PM', 'background', '10-JAN-18 11.05.04.000000000 PM', 'background');
	END; 
	BEGIN 
		SELECT VALUE INTO tmp2 FROM sparameter WHERE NAME='STORE_BID_RESULT_DATA_DIR'; 
	EXCEPTION
		WHEN no_data_found THEN
		INSERT INTO SPARAMETER (PARAMETER_KEY, NAME, VALUE, DESCRIPTION, SYSTEM, TYPE, MODIFIEDON, MODIFIEDBY, CREATEDON, CREATEDBY) VALUES ((SELECT MAX(PARAMETER_KEY)+1 FROM SPARAMETER), 'STORE_BID_RESULT_DATA_DIR', 'C:\ISO\STORE_BID_RESULT_DATA', '','GenManager', 'ISO', '10-JAN-18 11.05.04.000000000 PM', 'background', '10-JAN-18 11.05.04.000000000 PM', 'background');
	END; 
	UPDATE SSYS_ID SET NEXT_KEY = (SELECT MAX(PARAMETER_KEY) FROM SPARAMETER) WHERE ID_TYPE = 'PARAMETER';
	COMMIT;
END;