BEGIN
 	UPDATE SUSER SET U_PASSWORD = 'gtwp$pci1' WHERE U_NAME IN ('Admin','background');
	UPDATE SPARAMETER SET "VALUE" = 'gtwp$pci1' WHERE SYSTEM = 'GenPortal' and TYPE = '_SYSTEM_' and NAME = 'BACKGROUND_PASSWORD';
  
	UPDATE SUSER SET SOURCE = 'S';
	UPDATE SASSET_OWNER_CONFIG SET ACTIVE= 'N';

    UPDATE SPARAMETER SET VALUE = 'C:\ISONE\Archive' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'ARCHIVE_DIRECTORY';
    UPDATE SPARAMETER SET VALUE = 'C:\ISONE\Upload\Auto' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'AUTO_UPLOAD_DIRECTORY';
    UPDATE SPARAMETER SET VALUE = 'C:\ISONE\Certificates' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'CERTS_DIRECTORY';
    UPDATE SPARAMETER SET VALUE = 'C:\ISONE\Download' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'DOWNLOAD_DIRECTORY';
    UPDATE SPARAMETER SET VALUE = 'C:\ISONE\Invoice' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'INVOICE_DOWNLOAD_DIRECTORY';
    UPDATE SPARAMETER SET VALUE = 'gtwppci1' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'ISO_EXPRESS_PASSWORD';
    UPDATE SPARAMETER SET VALUE = 'pakundi@powercosts.com' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'ISO_EXPRESS_USER_NAME';
    UPDATE SPARAMETER SET VALUE = 'C:\ISONE\Settlements\Archive' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'SETTLEMENT_ARCHIVE_DIRECTORY';
    UPDATE SPARAMETER SET VALUE = 'C:\ISONE\Settlements\Download\SFTP' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'SFTP_DOWNLOAD_DIRECTORY';
    UPDATE SPARAMETER SET VALUE = 'C:\ISONE\Settlements\Statements' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'STATEMENT_LOAD_DIRECTORY';
    UPDATE SPARAMETER SET VALUE = 'C:\ISONE\Certificates\PCIKEY.keystore' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'TRUST_STORE';
    UPDATE SPARAMETER SET VALUE = 'tQJPeerA' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'TRUST_STORE_PASSWORD';
    UPDATE SPARAMETER SET VALUE = 'C:\ISONE\Invoice\Upload' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'UPLOAD_DIRECTORY';
    UPDATE SPARAMETER SET VALUE = 'S' WHERE SYSTEM = 'GenManager' and TYPE = 'ISONE' and NAME = 'USE_MODE';
  COMMIT;
END;