UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE  = 'azps5 pci-testx23886 (caiso_certificate_authority_issuing)',
    PASSWORD     = 'caisoteam',
    CERT_DETAILS = 'CN=AZPS5 PCI-TESTx23886,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'APS4',
        'APS5',
        'AZPE'
    )
);

UPDATE SASSET_OWNER_CONFIG
SET SETTLE = 'N'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'AZPE');

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\aps4pcighgcertificate' WHERE NAME = 'APS4_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\aps5sftpsettlementsserver' WHERE NAME = 'APS5_CERT';

UPDATE SCUSTOM_FIELD SET VALUE = 'rEdz6usy' WHERE NAME = 'APS4_CERT_PASSWORD';
UPDATE SCUSTOM_FIELD SET VALUE = 'znu15R7H' WHERE NAME = 'APS5_CERT_PASSWORD';

UPDATE SCUSTOM_FIELD SET VALUE = 'aps4pcighgcertificate' WHERE NAME = 'APS4_SFTP_USER';
UPDATE SCUSTOM_FIELD SET VALUE = 'aps5sftpsettlementsserver' WHERE NAME = 'APS5_SFTP_USER';