UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'pci prsc test merch systemx18173 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=PCI PRSC TEST MERCH SYSTEMx18173,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'AVAM',
        'AVAT',
        'AVISTA'
    )
);

UPDATE SASSET_OWNER_CONFIG
SET SETTLE = 'N'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'AVAT',
        'AVISTA'
    )
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'C:\CAISO\Settlements\SFTP\avwppcitestbo'
WHERE NAME IN (
    'AVAM_CERT',
    'AVAT_CERT',
    'AVWP_CERT'
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'urfPpl8l'
WHERE NAME IN (
    'AVAM_CERT_PASSWORD',
    'AVAT_CERT_PASSWORD',
    'AVWP_CERT_PASSWORD'
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'avwppcitestbo'
WHERE NAME IN (
    'AVAM_SFTP_USER',
    'AVAT_SFTP_USER',
    'AVWP_SFTP_USER'
);