UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE  = 'bepc pci caiso testx31393 (caiso_certificate_authority_issuing)',
    PASSWORD     = 'caisoteam',
    CERT_DETAILS = 'CN=BEPC PCI CAISO TESTx31393,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'BEPM');

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\pciprivatesftpkeyforcaisosftp' WHERE NAME = 'BEPM_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'Evx*m$6O9^Hd' WHERE NAME = 'BEPM_CERT_PASSWORD';
UPDATE SCUSTOM_FIELD SET VALUE = 'bepmpcicaisosftp' WHERE NAME = 'BEPM_SFTP_USER';