UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'pcioffsite itx15906 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=PCIOFFSITE ITx15906,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY = (
    SELECT so.ASSET_OWNER_KEY
    FROM SASSET_OWNER so
    INNER JOIN SISO_PORTFOLIO_MAPPING spm
        ON so.ISO_PORTFOLIO_MAPPING_KEY = spm.ISO_PORTFOLIO_MAPPING_KEY
    WHERE so.NAME = 'DTET'
    AND spm.NAME = 'CAISO'
);

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\DTECasioSftpPrivateOSSH-1' WHERE NAME = 'DTET_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'Password2023!' WHERE NAME = 'DTET_CERT_PASSWORD';
UPDATE SCUSTOM_FIELD SET VALUE = 'pciprodsettlements' WHERE NAME = 'DTET_SFTP_USER';