UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'lawmeimstagemapstage pci-mbsx17814 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=LAWMEIMSTAGEMAPSTAGE PCI-MBSx17814,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN  (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'LAWM',
        'LDWP'
    )
);

UPDATE SASSET_OWNER_CONFIG
SET SETTLE = 'N'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'LDWP');

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\pcilawmprod.ppk' WHERE NAME = 'LAWM_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'F4M3%BJ6KZ%P' WHERE NAME = 'LAWM_CERT_PASSWORD';
UPDATE SCUSTOM_FIELD SET VALUE = 'pcilawmprod' WHERE NAME = 'LAWM_SFTP_USER';
