UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'nve pci-neim1x20882 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=NVE PCI-NEIM1x20882,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'NEIM',
        'NVE1'
    )
);

UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'nve pci-nvpm1x20688 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=NVE PCI-NVPM1x20688,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'NVPM',
        'SPPC',
        'SPPN'
    )
);

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\neimpci' WHERE NAME = 'NEIM_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'J3aJ3oL7' WHERE NAME = 'NEIM_CERT_PASSWORD';
UPDATE SCUSTOM_FIELD SET VALUE = 'neimpci' WHERE NAME = 'NEIM_SFTP_USER';

UPDATE SCUSTOM_FIELD
SET VALUE = 'C:\CAISO\Settlements\SFTP\nveuser.openssh.id'
WHERE NAME IN (
    'NVPM_CERT',
    'SPPC_CERT',
    'SPPN_CERT'
);

UPDATE SCUSTOM_FIELD
SET VALUE = '13975xle'
WHERE NAME IN (
    'NVPM_CERT_PASSWORD',
    'SPPC_CERT_PASSWORD',
    'SPPN_CERT_PASSWORD'
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'xkle'
WHERE NAME IN (
    'NVPM_SFTP_USER',
    'SPPC_SFTP_USER',
    'SPPN_SFTP_USER'
);