UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'pci primary scid-testx26185 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=PCI PRIMARY SCID-TESTx26185,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY = (
    SELECT so.ASSET_OWNER_KEY
    FROM SASSET_OWNER so
    INNER JOIN SISO_PORTFOLIO_MAPPING spm
        ON so.ISO_PORTFOLIO_MAPPING_KEY = spm.ISO_PORTFOLIO_MAPPING_KEY
    WHERE so.NAME = 'P66T'
    AND spm.NAME = 'CAISO'
);

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\PROD_CAISO_PVTKEY' WHERE NAME = 'P66T_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'p66caisopvtkey' WHERE NAME = 'P66T_CERT_PASSWORD';
UPDATE SCUSTOM_FIELD SET VALUE = 'p66settlementuser' WHERE NAME = 'P66T_SFTP_USER';