UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'pci pgenx5795 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=PCI PGENx5795,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'PGEE',
        'PGEN'
    )
);

UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'pci portx5870 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=PCI PORTx5870,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'PORT');

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\pgenpciaccessserver' WHERE NAME = 'PGEN_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\portpciaccessserver' WHERE NAME = 'PORT_CERT';

UPDATE SCUSTOM_FIELD SET VALUE = '8IGLZRCx' WHERE NAME = 'PGEN_CERT_PASSWORD';
UPDATE SCUSTOM_FIELD SET VALUE = 'sp5yrG1R' WHERE NAME = 'PORT_CERT_PASSWORD';

UPDATE SCUSTOM_FIELD SET VALUE = 'pgenpciaccessserver' WHERE NAME = 'PGEN_SFTP_USER';
UPDATE SCUSTOM_FIELD SET VALUE = 'portpciaccessserver' WHERE NAME = 'PORT_SFTP_USER';