UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'pci test user2x16632 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=PCI TEST USER2x16632,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'EXC_TEPM_1996',
        'EXC_TEPM_2144',
        'NMJU',
        'NMPR',
        'PNMM'
    )
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'C:\CAISO\Settlements\SFTP\PNM_Private.ppk'
WHERE NAME IN (
    'NMJU_CERT',
    'NMPR_CERT',
    'PNMM_CERT'
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'GoCowboys0321!'
WHERE NAME IN (
    'NMJU_CERT_PASSWORD',
    'NMPR_CERT_PASSWORD',
    'PNMM_CERT_PASSWORD'
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'pcipnmsettlements2'
WHERE NAME IN (
    'NMJU_SFTP_USER',
    'NMPR_SFTP_USER',
    'PNMM_SFTP_USER'
);