UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'pci system load officex4117 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=PCI SYSTEM LOAD OFFICEx4117,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'PSE2',        
        'PUG1',        
        'PUGETSOUND'        
    )
);

UPDATE SASSET_OWNER_CONFIG
SET SETTLE = 'N'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'PSE2',
        'PUGETSOUND'
    )
);

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\pug1pci_system' WHERE NAME = 'PUG1_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'pfD6KCtK' WHERE NAME = 'PUG1_CERT_PASSWORD';
UPDATE SCUSTOM_FIELD SET VALUE = 'pug1pci_system' WHERE NAME = 'PUG1_SFTP_USER';