UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'trade floor pci prod rox5676 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=TRADE FLOOR PCI PROD ROx5676,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'PSE1',
        'PSE2',
        'PSEI_BA',
        'PUG1',
        'PUGETSOUND'
    )
);

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\pse1accessserver' WHERE NAME = 'PSE1_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\pse2accessserver' WHERE NAME = 'PSE2_CERT';

UPDATE SCUSTOM_FIELD SET VALUE = 'ENCaM6r4' WHERE NAME = 'PSE1_CERT_PASSWORD';
UPDATE SCUSTOM_FIELD SET VALUE = '08dJJgli' WHERE NAME = 'PSE2_CERT_PASSWORD';

UPDATE SCUSTOM_FIELD SET VALUE = 'pse1accessserver' WHERE NAME = 'PSE1_SFTP_USER';
UPDATE SCUSTOM_FIELD SET VALUE = 'pse2accessserver' WHERE NAME = 'PSE2_SFTP_USER';