UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE  = 'pci ro schedulingx25361 (caiso_certificate_authority_issuing)',
    PASSWORD     = 'caisoteam',
    CERT_DETAILS = 'CN=PCI RO SCHEDULINGx25361,OU=people,O=CAISO,C=US',
    ACTIVE       = 'Y'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'CEE1');

UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE  = 'pci testx24167 (caiso_certificate_authority_issuing)',
    PASSWORD     = 'caisoteam',
    CERT_DETAILS = 'CN=PCI TESTx24167,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'QRWE');

UPDATE SCUSTOM_FIELD
SET VALUE = 'C:\CAISO\Settlements\SFTP\rwesettlements.ppk'
WHERE NAME IN (
    'CEE1_CERT',
    'QRWE_CERT'
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'qrwesettl123'
WHERE NAME IN (
    'CEE1_CERT_PASSWORD',
    'QRWE_CERT_PASSWORD'
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'rwesettlements'
WHERE NAME IN (
    'CEE1_SFTP_USER',
    'QRWE_SFTP_USER'
);