UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'sdge sdgemapx14542 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=SDGE SDGEMAPx14542,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'APXO',
        'EXC_FPPM_510',
        'EXC_PCPM_532',
        'EXC_PCPM_533',
        'EXC_PCPM_534',
        'EXC_VSN2_505',
        'SDG3',
        'SDGP',
        'SDGW'
    )
);

UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'N',
    SETTLE = 'N'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'SDGP',
        'SDGW'
    )
);

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\SDGE_Private_Key.ppk' WHERE NAME = 'SDG3_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'Sempra123!' WHERE NAME = 'SDG3_CERT_PASSWORD';
UPDATE SCUSTOM_FIELD SET VALUE = 'sdgesettlementspci' WHERE NAME = 'SDG3_SFTP_USER';