UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'srp pci-srp-test-tgox13356 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=SRP PCI-SRP-TEST-TGOx13356,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'SALTRIVER',
        'SRP',
        'SRP_BA',
        'SRPE',
        'SRPM'
    )
);

UPDATE SASSET_OWNER_CONFIG
SET SETTLE = 'N'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'SALTRIVER',
        'SRP',
        'SRP_BA',
        'SRPM'
    )
);

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\SRPEPrivate key.ppk' WHERE NAME = 'SRPE_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'phoenixWPB113!' WHERE NAME = 'SRPE_CERT_PASSWORD';
UPDATE SCUSTOM_FIELD SET VALUE = 'pcisrpeserveraccess' WHERE NAME = 'SRPE_SFTP_USER';