UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'pci testx14350 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=PCI TESTx14350,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY = (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'TCM1');

UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'pci tpwm-testx18225 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=PCI TPWM-TESTx18225,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'TPWE',
        'TPWM',
        'TPWR_BA'
    )
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'C:\CAISO\Settlements\SFTP\TPU_BO_Private.ppk'
WHERE NAME IN (
    'TCM1_CERT',
    'TPWM_CERT'
);

UPDATE SCUSTOM_FIELD
SET VALUE = '2020PCItpuCERT'
WHERE NAME IN (
    'TCM1_CERT_PASSWORD',
    'TPWM_CERT_PASSWORD'
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'ppciprod'
WHERE NAME IN (
    'TCM1_SFTP_USER',
    'TPWM_SFTP_USER'
);