UPDATE SASSET_OWNER_CONFIG SET CERTIFICATE = 'pci tpwe-bo-testx18484 (caiso_certificate_authority_issuing)', PASSWORD = 'caisoteam', CERT_DETAILS = 'CN=PCI TPWE-BO-TESTx18484,OU=people,O=CAISO,C=US';

UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\SFTP_CERTS\CAISO-Settlements\TPU-BO\TPWE_BO_Private.ppk' WHERE NAME = 'TCM1_CERT';
UPDATE SCUSTOM_FIELD SET VALUE = 'C:\CAISO\Settlements\SFTP\SFTP_CERTS\CAISO-Settlements\TPU-BO\TPWE_BO_Private.ppk' WHERE NAME = 'TPWE_CERT';