UPDATE SASSET_OWNER_CONFIG
SET
    CERTIFICATE = 'pci scid-testx20906 (caiso_certificate_authority_issuing)',
    PASSWORD = 'caisoteam',
    CERT_DETAILS = 'CN=PCI SCID-TESTx20906,OU=people,O=CAISO,C=US'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME IN (
        'EXC_PACE_2116',
        'EXC_PACE_2156',
        'PACE',
        'UMPA',
        'UMPL',
        'UTPR'
    )
);

UPDATE SASSET_OWNER_CONFIG
SET SETTLE = 'N'
WHERE ASSET_OWNER_KEY IN (SELECT ASSET_OWNER_KEY FROM SASSET_OWNER WHERE NAME = 'UMPL');

UPDATE SCUSTOM_FIELD
SET VALUE = 'C:\CAISO\Settlements\SFTP\UMPA_Private'
WHERE NAME IN (
    'UMPA_CERT',
    'UTPR_CERT'
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'Umpa1234'
WHERE NAME IN (
    'UMPA_CERT_PASSWORD',
    'UTPR_CERT_PASSWORD'
);

UPDATE SCUSTOM_FIELD
SET VALUE = 'umpasettlements'
WHERE NAME IN (
    'UMPA_SFTP_USER',
    'UTPR_SFTP_USER'
);