UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y',
	CERTIFICATE = 'C:\NYISO\Certificates\PCITestCASS 121224.pfx',
    PASSWORD = 'Password123',
-- MIS_USER
    USER1 = 'CASSTEST',
-- MIS_PASSWORD
    USER2 = 'Password123!',
-- DSS_USER
    USER3 = 'godeced1',
-- DSS_PASSWORD
    USER4 = 'Pci2023!'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'CASS'
);

UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y',
	CERTIFICATE = 'C:\NYISO\Certificates\PCIMUNNTESTRW.pfx',
    PASSWORD = 'Javier1!',
-- MIS_USER
    USER1 = 'MUNN_RW',
-- MIS_PASSWORD
    USER2 = 'rwemunntes2026',
-- DSS_USER
    USER3 = 'settlco1',
-- DSS_PASSWORD
    USER4 = 'settlement12?'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'RWECLEANENERGY'
);

UPDATE SASSET_OWNER_CONFIG
SET 
    ACTIVE = 'Y',
	CERTIFICATE = 'C:\NYISO\Certificates\QSE_TEST.pfx',
    PASSWORD = 'Password123!',
-- MIS_USER
    USER1 = 'RWEPCI2',
-- MIS_PASSWORD
    USER2 = 'Password123!',
-- DSS_USER
    USER3 = 'settlrw2',
-- DSS_PASSWORD
    USER4 = 'Pci1234!'
WHERE ASSET_OWNER_KEY IN (
    SELECT ASSET_OWNER_KEY FROM SASSET_OWNER
    WHERE NAME = 'RWERENWQSE'
);